export type VehicleType = 'standard' | 'comfort' | 'xl';
export type Vehicle = { id: VehicleType; title: string; description: string; seats: number; multiplier: number };
export type AppConfig = {
  vehicles: Vehicle[];
  cities: string[];
  documentKinds: string[];
  acceptingRides: boolean;
  momoAvailable: boolean;
  mapsProvider: 'google' | 'openstreetmap';
  offerSeconds: number;
};
export type Place = { address: string; lat: number; lng: number };
export type Profile = { userId: string; name: string; phone: string; email: string };
export type DocumentInfo = { kind: string; id: number | null; filename?: string; size?: number; uploadedAt?: string };
export type Driver = {
  userId: string;
  name: string;
  phone: string;
  email: string;
  city: string;
  vehicleType: VehicleType;
  vehicleModel: string;
  vehicleColor: string;
  plate: string;
  licenceNumber: string;
  status: 'pending' | 'approved' | 'rejected' | 'suspended';
  reviewNote: string | null;
  online: boolean;
  lat: number | null;
  lng: number | null;
  locationAt: string | null;
  createdAt: string;
  documents: DocumentInfo[];
};
export type Me = {
  user: { id: string; email: string; name: string; isAdmin: boolean };
  profile: Profile | null;
  driver: Driver | null;
  activeRideId: number | null;
};
export type RideStatus = 'searching' | 'offered' | 'accepted' | 'arrived' | 'in_progress' | 'completed' | 'cancelled';
export type Ride = {
  id: number;
  status: RideStatus;
  pickupAddress: string;
  pickupLat: number;
  pickupLng: number;
  dropoffAddress: string;
  dropoffLat: number;
  dropoffLng: number;
  vehicleType: VehicleType;
  distanceKm: number;
  durationMin: number;
  fare: number;
  paymentMethod: 'cash' | 'momo';
  paymentStatus: 'unpaid' | 'pending' | 'paid' | 'cash_collected';
  riderRating: number | null;
  cancelReason: string | null;
  cancelledBy: string | null;
  createdAt: string;
  completedAt: string | null;
  driver: {
    name: string;
    phone: string | null;
    vehicleModel: string;
    vehicleColor: string;
    plate: string;
    lat: number | null;
    lng: number | null;
  } | null;
};
export type Job = {
  id: number;
  status: RideStatus;
  riderName: string;
  riderPhone: string | null;
  pickupAddress: string;
  pickupLat: number;
  pickupLng: number;
  dropoffAddress: string;
  dropoffLat: number;
  dropoffLng: number;
  vehicleType: VehicleType;
  distanceKm: number;
  durationMin: number;
  fare: number;
  driverEarnings: number;
  paymentMethod: 'cash' | 'momo';
  paymentStatus: string;
  offerExpiresAt: string | null;
  completedAt: string | null;
  createdAt: string;
};
